### PR TITLE
fix(trie): gate metrics-only imports behind feature flag

### PR DESCRIPTION
**Pull request by niran**
## Summary

- Gate `eyre::WrapErr` and `tracing::error` imports in `store.rs` behind `#[cfg(feature = "metrics")]` since they are only used in metrics impl blocks
- Suppress `missing_const_for_fn` on `OpProofStoragePruner::new` — the lint fires without `metrics` but the function cannot be `const` when `metrics` is enabled (due to `Metrics::default()`)

## Context

`base-execution-trie` fails to compile when built individually (without the `metrics` feature):

```
error[E0432]: unresolved import `eyre`
error: unused import: `tracing::error`
```

Full workspace builds mask this because they enable `metrics` transitively.

The root cause is upstream: commit `be39a17` (op-rs/op-reth#407) added these imports unconditionally, then `3ebb5d7` (op-rs/op-reth#627) made `eyre` an optional dep gated behind `metrics` without updating the imports. Our `c8b2337` (#875) hoisted the imports to file-level, preserving the bug.

## Test plan

- [x] `cargo clippy -p base-execution-trie --profile ci -- -D warnings` (without metrics)
- [x] `cargo clippy -p base-execution-trie --profile ci --features metrics -- -D warnings` (with metrics)

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>✅ Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
✅
<code>1/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td><code>2</code> if repo is sensitive</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Comment by danyalprout** [comment]
@refcell what do you think about just removing this flag? curious if there's a good reason to cfg flag metrics

File: crates/execution/trie/src/prune/pruner.rs [hunk 1]
```diff
@@ -31,6 +31,7 @@ pub struct OpProofStoragePruner<P, H> {
 
 impl<P, H> OpProofStoragePruner<P, H> {
     /// Create a new pruner.
+    #[allow(clippy::missing_const_for_fn)] // not const when `metrics` feature enables Metrics::default()
```
Comment (refcell) [inline crates/execution/trie/src/prune/pruner.rs:34]: I'm surprised this doesn't upset clippy before this addition and after (ci is happy in this pr).

**Review by refcell — APPROVED** [review]
